In [56]:
import pandas as pd
import numpy as np

data = {'Country': ['Belgium', 'India', 'Brazil'],
        'Capital': ['Brussels', 'New Delhi', 'Brasília'],
        'Population': [11190846, 1303171035, 207847528]
       }

In [57]:
df = pd.DataFrame(data, columns=['Country', 'Capital', 'Population'])
df

Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasília   207847528

In [10]:
df[2:] # third row

Country   Capital  Population
2  Brazil  Brasília   207847528

In [58]:
df[:2] # everything but not including 3rd row

Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035

In [11]:
df.ix[:,'Capital'] 

0     Brussels
1    New Delhi
2     Brasília
Name: Capital, dtype: object

In [12]:
df.columns

Index([u'Country', u'Capital', u'Population'], dtype='object')

In [13]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [14]:
transactions = pd.DataFrame({
    'TransactionID': np.arange(10)+1,
    'TransactionDate': pd.to_datetime(['2010-08-21', '2011-05-26', '2011-06-16', '2012-08-26', '2013-06-06', 
                              '2013-12-23', '2013-12-30', '2014-04-24', '2015-04-24', '2016-05-08']).date,
    'UserID': [7, 3, 3, 1, 2, 2, 3, np.nan, 7, 3],
    'ProductID': [2, 4, 3, 2, 4, 5, 4, 2, 4, 4],
    'Quantity': [1, 1, 1, 3, 1, 6, 1, 3, 3, 4]
})

How many rows?

In [16]:
transactions.shape[0]

10

How many columns?

In [17]:
transactions.shape[1]

5

Get the column names 

In [20]:
transactions.columns.values

Index([u'ProductID', u'Quantity', u'TransactionDate', u'TransactionID',
       u'UserID'],
      dtype='object')

Change the name of column "Quantity" to "Quant"

In [23]:
transactions.rename(columns={'Quantity': 'Quant'}, inplace = 'TRUE')  # use argument inplace=TRUE to keep the changes

In [24]:
transactions

ProductID  Quant TransactionDate  TransactionID  UserID
0          2      1      2010-08-21              1     7.0
1          4      1      2011-05-26              2     3.0
2          3      1      2011-06-16              3     3.0
3          2      3      2012-08-26              4     1.0
4          4      1      2013-06-06              5     2.0
5          5      6      2013-12-23              6     2.0
6          4      1      2013-12-30              7     3.0
7          2      3      2014-04-24              8     NaN
8          4      3      2015-04-24              9     7.0
9          4      4      2016-05-08             10     3.0

Change the name of columns ProductID and UserID to PID and UID respectively

In [25]:
transactions.rename(columns={'ProductID': 'PID', 'UserID': 'UID'})  # use argument inplace=TRUE to keep the changes

PID  Quant TransactionDate  TransactionID  UID
0    2      1      2010-08-21              1  7.0
1    4      1      2011-05-26              2  3.0
2    3      1      2011-06-16              3  3.0
3    2      3      2012-08-26              4  1.0
4    4      1      2013-06-06              5  2.0
5    5      6      2013-12-23              6  2.0
6    4      1      2013-12-30              7  3.0
7    2      3      2014-04-24              8  NaN
8    4      3      2015-04-24              9  7.0
9    4      4      2016-05-08             10  3.0

Order the rows of transactions by TransactionID descending 

In [26]:
transactions.sort_values('TransactionID', ascending=False)

ProductID  Quant TransactionDate  TransactionID  UserID
9          4      4      2016-05-08             10     3.0
8          4      3      2015-04-24              9     7.0
7          2      3      2014-04-24              8     NaN
6          4      1      2013-12-30              7     3.0
5          5      6      2013-12-23              6     2.0
4          4      1      2013-06-06              5     2.0
3          2      3      2012-08-26              4     1.0
2          3      1      2011-06-16              3     3.0
1          4      1      2011-05-26              2     3.0
0          2      1      2010-08-21              1     7.0

Order the rows of transactions by Quantity ascending, TransactionDate descending

In [31]:
transactions.sort_values(['Quant', 'TransactionDate'], ascending=[True, False])

ProductID  Quant TransactionDate  TransactionID  UserID
6          4      1      2013-12-30              7     3.0
4          4      1      2013-06-06              5     2.0
2          3      1      2011-06-16              3     3.0
1          4      1      2011-05-26              2     3.0
0          2      1      2010-08-21              1     7.0
8          4      3      2015-04-24              9     7.0
7          2      3      2014-04-24              8     NaN
3          2      3      2012-08-26              4     1.0
9          4      4      2016-05-08             10     3.0
5          5      6      2013-12-23              6     2.0

# Extracting arrays from a DataFrame 

In [32]:
transactions

ProductID  Quant TransactionDate  TransactionID  UserID
0          2      1      2010-08-21              1     7.0
1          4      1      2011-05-26              2     3.0
2          3      1      2011-06-16              3     3.0
3          2      3      2012-08-26              4     1.0
4          4      1      2013-06-06              5     2.0
5          5      6      2013-12-23              6     2.0
6          4      1      2013-12-30              7     3.0
7          2      3      2014-04-24              8     NaN
8          4      3      2015-04-24              9     7.0
9          4      4      2016-05-08             10     3.0

Get the 2nd column

In [33]:
transactions[[1]].values[:, 0]

array([1, 1, 1, 3, 1, 6, 1, 3, 3, 4], dtype=int64)

Get the ProductID array

In [34]:
transactions.ProductID.values

array([2, 4, 3, 2, 4, 5, 4, 2, 4, 4], dtype=int64)

Get the ProductID array using a variable

In [35]:
col = "ProductID"
transactions[[col]].values[:, 0]

array([2, 4, 3, 2, 4, 5, 4, 2, 4, 4], dtype=int64)

Row subsetting 

Subset rows 1, 3, and 6

In [36]:
transactions.iloc[[0,2,5]]

ProductID  Quant TransactionDate  TransactionID  UserID
0          2      1      2010-08-21              1     7.0
2          3      1      2011-06-16              3     3.0
5          5      6      2013-12-23              6     2.0

Subset rows exlcuding 1, 3, and 6

In [37]:
transactions.drop([0,2,5], axis=0)

ProductID  Quant TransactionDate  TransactionID  UserID
1          4      1      2011-05-26              2     3.0
3          2      3      2012-08-26              4     1.0
4          4      1      2013-06-06              5     2.0
6          4      1      2013-12-30              7     3.0
7          2      3      2014-04-24              8     NaN
8          4      3      2015-04-24              9     7.0
9          4      4      2016-05-08             10     3.0

Subset the first 3 rows

In [38]:
transactions[:3]

ProductID  Quant TransactionDate  TransactionID  UserID
0          2      1      2010-08-21              1     7.0
1          4      1      2011-05-26              2     3.0
2          3      1      2011-06-16              3     3.0

Subset rows excluding the first 3 rows

In [39]:
transactions[3:]

ProductID  Quant TransactionDate  TransactionID  UserID
3          2      3      2012-08-26              4     1.0
4          4      1      2013-06-06              5     2.0
5          5      6      2013-12-23              6     2.0
6          4      1      2013-12-30              7     3.0
7          2      3      2014-04-24              8     NaN
8          4      3      2015-04-24              9     7.0
9          4      4      2016-05-08             10     3.0

Subset the last 2 rows

In [40]:
transactions.tail(2)

ProductID  Quant TransactionDate  TransactionID  UserID
8          4      3      2015-04-24              9     7.0
9          4      4      2016-05-08             10     3.0

Subset rows where Quantity > 1

In [41]:
transactions[transactions.Quant > 1]

ProductID  Quant TransactionDate  TransactionID  UserID
3          2      3      2012-08-26              4     1.0
5          5      6      2013-12-23              6     2.0
7          2      3      2014-04-24              8     NaN
8          4      3      2015-04-24              9     7.0
9          4      4      2016-05-08             10     3.0

Subset rows where Quantity > 1 and UserID = 2 

In [42]:
transactions[(transactions.Quant > 1) & (transactions.UserID == 2)]

ProductID  Quant TransactionDate  TransactionID  UserID
5          5      6      2013-12-23              6     2.0

# Column subsetting

Subset by columns 1 and 3 

In [43]:
transactions.iloc[:, [0, 2]]

ProductID TransactionDate
0          2      2010-08-21
1          4      2011-05-26
2          3      2011-06-16
3          2      2012-08-26
4          4      2013-06-06
5          5      2013-12-23
6          4      2013-12-30
7          2      2014-04-24
8          4      2015-04-24
9          4      2016-05-08

Subset by column names TransactionID and TransactionDate

In [44]:
transactions[['TransactionID', 'TransactionDate']]

TransactionID TransactionDate
0              1      2010-08-21
1              2      2011-05-26
2              3      2011-06-16
3              4      2012-08-26
4              5      2013-06-06
5              6      2013-12-23
6              7      2013-12-30
7              8      2014-04-24
8              9      2015-04-24
9             10      2016-05-08

Subset rows where TransactionID > 5 and subset columns by TransactionID and TransactionDate

In [46]:
transactions.loc[transactions.TransactionID > 5, ['TransactionID', 'TransactionDate']]

TransactionID TransactionDate
5              6      2013-12-23
6              7      2013-12-30
7              8      2014-04-24
8              9      2015-04-24
9             10      2016-05-08

Subset columns excluding a variable list of column names

In [48]:
cols = ["TransactionID", "UserID", "Quant"]
transactions.drop(cols, axis=1)

ProductID TransactionDate
0          2      2010-08-21
1          4      2011-05-26
2          3      2011-06-16
3          2      2012-08-26
4          4      2013-06-06
5          5      2013-12-23
6          4      2013-12-30
7          2      2014-04-24
8          4      2015-04-24
9          4      2016-05-08

# Inserting and updating values

Convert the TransactionDate column to type Date

In [49]:
transactions['TransactionDate'] = pd.to_datetime(transactions.TransactionDate)
transactions

Insert a new column, Foo = UserID + ProductID

In [51]:
transactions['Foo'] = transactions.UserID + transactions.ProductID

Insert a column indicating each row number

In [53]:
transactions['RowIdx'] = np.arange(transactions.shape[0])
transactions

ProductID  Quant TransactionDate  TransactionID  UserID   Foo  RowIdx
0          2      1      2010-08-21              1     7.0   9.0       0
1          4      1      2011-05-26              2     3.0   7.0       1
2          3      1      2011-06-16              3     3.0   6.0       2
3          2      3      2012-08-26              4     1.0   3.0       3
4          4      1      2013-06-06              5     2.0   6.0       4
5          5      6      2013-12-23              6     2.0   7.0       5
6          4      1      2013-12-30              7     3.0   7.0       6
7          2      3      2014-04-24              8     NaN   NaN       7
8          4      3      2015-04-24              9     7.0  11.0       8
9          4      4      2016-05-08             10     3.0   7.0       9

Remove column Foo

In [54]:
transactions.drop('Foo', axis=1, inplace=True) # multiple columns (put them in a list)

Group the transations per user, measuring the number of transactions per user

In [55]:
transactions.groupby('UserID').apply(lambda x: pd.Series(dict(
    Transactions=x.shape[0],
))).reset_index()

UserID  Transactions
0     1.0             1
1     2.0             2
2     3.0             4
3     7.0             2

dataframe joins

In [ ]:
#transactions.merge(users, how='left', on='UserID')